// Next
import type { Metadata } from "next";
import { Sen } from "next/font/google";
// Styles
import "@/app/globals.css";
import Footer from "@/components/layout/footer";
// Third-party
import { Analytics } from "@vercel/analytics/react"

// Fonts
const mainFont = Sen({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

// Metas
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${mainFont.className} antialiased`}
      >
        {children}
        <Footer />
        <Analytics />
      </body>
    </html>
  );
}
